spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/twins
    username: twins
    password: twins123
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092